# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 450)
        Form.setMinimumSize(QtCore.QSize(600, 450))
        Form.setMaximumSize(QtCore.QSize(500, 450))
        Form.setStyleSheet("QWidget#Form{\n"
"border-image: url(:/register/images/back.jpg);\n"
"}")
        self.main_menu_button = QtWidgets.QPushButton(Form)
        self.main_menu_button.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.main_menu_button.setCheckable(True)
        self.main_menu_button.setObjectName("main_menu_button")
        self.exit_menue_btn = QtWidgets.QPushButton(Form)
        self.exit_menue_btn.setGeometry(QtCore.QRect(100, 10, 50, 50))
        self.exit_menue_btn.setStyleSheet("QPushButton{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(75, 101, 132);\n"
"color:white;\n"
"}")
        self.exit_menue_btn.setCheckable(False)
        self.exit_menue_btn.setObjectName("exit_menue_btn")
        self.about_menue_btn = QtWidgets.QPushButton(Form)
        self.about_menue_btn.setGeometry(QtCore.QRect(70, 60, 50, 50))
        self.about_menue_btn.setStyleSheet("QPushButton{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(75, 101, 132);\n"
"color:white;\n"
"}")
        self.about_menue_btn.setCheckable(False)
        self.about_menue_btn.setObjectName("about_menue_btn")
        self.reset_menue_btn = QtWidgets.QPushButton(Form)
        self.reset_menue_btn.setGeometry(QtCore.QRect(10, 90, 50, 50))
        self.reset_menue_btn.setStyleSheet("QPushButton{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(75, 101, 132);\n"
"color:white;\n"
"}")
        self.reset_menue_btn.setCheckable(False)
        self.reset_menue_btn.setObjectName("reset_menue_btn")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 140, 211, 223))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font: 13pt \"STHeiti\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.account_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.account_le.setMinimumSize(QtCore.QSize(0, 30))
        self.account_le.setClearButtonEnabled(True)
        self.account_le.setObjectName("account_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.account_le)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font: 13pt \"STHeiti\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.passward_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.passward_le.setMinimumSize(QtCore.QSize(0, 30))
        self.passward_le.setClearButtonEnabled(True)
        self.passward_le.setObjectName("passward_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passward_le)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font: 13pt \"STHeiti\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.confirm_pwd_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirm_pwd_le.setMinimumSize(QtCore.QSize(0, 30))
        self.confirm_pwd_le.setClearButtonEnabled(True)
        self.confirm_pwd_le.setObjectName("confirm_pwd_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confirm_pwd_le)
        self.register_button = QtWidgets.QPushButton(self.layoutWidget)
        self.register_button.setEnabled(False)
        self.register_button.setMinimumSize(QtCore.QSize(0, 45))
        self.register_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(209, 216, 224);\n"
"border-radius:40px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(165, 177, 194);\n"
"border-radius:40px;\n"
"}\n"
"\n"
"\n"
"QPushButton:dissabled{\n"
"background-color:rgb(241, 242, 246) ;\n"
"border-radius:40px;\n"
"}\n"
"font: 13pt \".AppleSystemUIFont\";")
        self.register_button.setObjectName("register_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.register_button)
        self.exit_menue_btn.raise_()
        self.about_menue_btn.raise_()
        self.reset_menue_btn.raise_()
        self.layoutWidget.raise_()
        self.main_menu_button.raise_()

        self.retranslateUi(Form)
        self.main_menu_button.clicked['bool'].connect(Form.show_hide_menu)
        self.exit_menue_btn.clicked.connect(Form.tuichu_fun)
        self.about_menue_btn.clicked.connect(Form.guanyu_fun)
        self.reset_menue_btn.clicked.connect(Form.chongzhi_fun)
        self.register_button.clicked.connect(Form.check_register)
        self.account_le.textChanged['QString'].connect(Form.enable_register_btn)
        self.passward_le.textChanged['QString'].connect(Form.enable_register_btn)
        self.confirm_pwd_le.textChanged['QString'].connect(Form.enable_register_btn)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_menu_button.setStyleSheet(_translate("Form", "QPushButton{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(119, 140, 163);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"font: 12pt \"STHeiti\";\n"
"border-radius:25px;\n"
"background-color:rgb(75, 101, 132);\n"
"color:white;\n"
"}"))
        self.main_menu_button.setText(_translate("Form", "菜单"))
        self.exit_menue_btn.setText(_translate("Form", "退出"))
        self.about_menue_btn.setText(_translate("Form", "关于"))
        self.reset_menue_btn.setText(_translate("Form", "重置"))
        self.label.setText(_translate("Form", "账号："))
        self.label_3.setText(_translate("Form", "密码："))
        self.label_2.setText(_translate("Form", "确认密码："))
        self.register_button.setText(_translate("Form", "注册"))
import images_rc
