# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 450)
        Form.setMinimumSize(QtCore.QSize(500, 450))
        Form.setMaximumSize(QtCore.QSize(500, 450))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.login_top_bg_label = QtWidgets.QLabel(self.widget)
        self.login_top_bg_label.setGeometry(QtCore.QRect(170, 10, 160, 160))
        self.login_top_bg_label.setMinimumSize(QtCore.QSize(160, 160))
        self.login_top_bg_label.setText("")
        self.login_top_bg_label.setObjectName("login_top_bg_label")
        self.verticalLayout.addWidget(self.widget)
        self.login_bottom = QtWidgets.QWidget(Form)
        self.login_bottom.setStyleSheet("")
        self.login_bottom.setObjectName("login_bottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.login_bottom)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.login_bottom)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.widget_3 = QtWidgets.QWidget(self.login_bottom)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.pwd_le = QtWidgets.QLineEdit(self.widget_3)
        self.pwd_le.setMinimumSize(QtCore.QSize(0, 30))
        self.pwd_le.setStyleSheet("QLineEdit{\n"
"font-size:13px;\n"
"border:none;\n"
"border-bottom: 1px solid lightgray;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border-bottom:1px solid gray;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom:1px solid rgb(18,183,245);\n"
"}")
        self.pwd_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_le.setClearButtonEnabled(True)
        self.pwd_le.setObjectName("pwd_le")
        self.gridLayout.addWidget(self.pwd_le, 1, 0, 1, 2)
        self.auto_login_cb = QtWidgets.QCheckBox(self.widget_3)
        self.auto_login_cb.setObjectName("auto_login_cb")
        self.gridLayout.addWidget(self.auto_login_cb, 2, 0, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.widget_3)
        self.login_btn.setEnabled(False)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.login_btn.setStyleSheet("QPushButton{\n"
"background-color:rgb(33,174,250);\n"
"border-radius:8px;\n"
"color:white;\n"
"spacing:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(72,203,250);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(85,85,255);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color:rgb(167,167,167);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/images/login_btn_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_btn.setIcon(icon)
        self.login_btn.setIconSize(QtCore.QSize(20, 20))
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 3, 0, 1, 2)
        self.remember_pwd_cb = QtWidgets.QCheckBox(self.widget_3)
        self.remember_pwd_cb.setObjectName("remember_pwd_cb")
        self.gridLayout.addWidget(self.remember_pwd_cb, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.account_cb = QtWidgets.QComboBox(self.widget_3)
        self.account_cb.setMinimumSize(QtCore.QSize(100, 10))
        self.account_cb.setMaximumSize(QtCore.QSize(16777215, 40))
        self.account_cb.setStyleSheet("QComboBox{\n"
"font-size:12px;\n"
"border:none;\n"
"border-bottom:1px solid lightgray;\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"\n"
"border-bottom:1px solid gray;\n"
"\n"
"}\n"
"\n"
"QComboBox:focus{\n"
"\n"
"border-bottom:1px solid rgb(18,183,245);\n"
"\n"
"}\n"
"\n"
"QComboBox:drop-down{\n"
"background-color:transparent;\n"
"width:60px;\n"
"height:40px;\n"
"}\n"
"\n"
"QComboBox:down-arrow{\n"
"image: url(:/login/images/login_arrow.png);\n"
"width:60px;\n"
"height:20px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView{\n"
"min-height:60px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView:item{\n"
"color:lightblue;\n"
"}")
        self.account_cb.setEditable(True)
        self.account_cb.setObjectName("account_cb")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/login/images/deguo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account_cb.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/login/images/faguo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account_cb.addItem(icon2, "")
        self.gridLayout.addWidget(self.account_cb, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.login_bottom)
        self.pushButton_2.setMinimumSize(QtCore.QSize(10, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_2.setStyleSheet("border-image: url(:/login/images/login_erwei.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addWidget(self.login_bottom)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 3)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.show_register_pane)
        self.pushButton_2.clicked.connect(Form.open_qq_link)
        self.account_cb.editTextChanged['QString'].connect(Form.enable_login_btn)
        self.pwd_le.textChanged['QString'].connect(Form.enable_login_btn)
        self.login_btn.clicked.connect(Form.check_loign)
        self.auto_login_cb.clicked['bool'].connect(Form.auto_login)
        self.remember_pwd_cb.clicked['bool'].connect(Form.remember_pwd)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "注册账号"))
        self.auto_login_cb.setText(_translate("Form", "自动登录"))
        self.login_btn.setText(_translate("Form", "安全登录"))
        self.remember_pwd_cb.setText(_translate("Form", "记住密码"))
        self.account_cb.setItemText(0, _translate("Form", "1125408974"))
        self.account_cb.setItemText(1, _translate("Form", "23456"))
import images_rc
